INSERT  INTO tb_roles (role_id, name) VALUES (1, 'ADMIN') ON CONFLICT DO NOTHING;
INSERT  INTO tb_roles (role_id, name) VALUES (2, 'RECEPTIONIST') ON CONFLICT DO NOTHING;
INSERT  INTO tb_roles (role_id, name) VALUES (3, 'ATTENDANT_G1') ON CONFLICT DO NOTHING;
INSERT  INTO tb_roles (role_id, name) VALUES (4, 'ATTENDANT_G2') ON CONFLICT DO NOTHING;